### ISSUE TITLE
Unable to import the module [vs code and the package itself]

### ISSUE THREAD

**Issue by EpicBirb** [discord-py-ui/discord-ui#112]
VS code:
![image](https://user-images.githubusercontent.com/68750348/145481377-0380d83f-cc72-4310-ba63-115903b20bdc.png)

Python interpreter:
![image](https://user-images.githubusercontent.com/68750348/145481595-82d2a145-ada4-47a5-bdcd-33fa9b27e68b.png)

**Comment by EpicBirb** [comment]
also.
without using `import discord_ui`
it will have the NoModuleFoundError because of line 29

**Comment by RedstoneZockt** [comment]
Can u try to remove the .client after discord_ui? 
so: `from discord_ui import UI`

**Comment by 404kuso** [comment]
seems like imports in nextcord are a bit different, I'll fix that, sorry for the trouble

**Comment by 404kuso** [comment]
alrighty, that issue should be fixed in [v5.1.2](https://github.com/discord-py-ui/discord-ui/releases/tag/v5.1.2), thanks for reporting and sorry for the wait.

I'll leave this issue open in case the issue should still exsist or you still got any problems, if it's fixed for you, just close the issue :)

**Comment by EpicBirb** [comment]
![image](https://user-images.githubusercontent.com/68750348/145652298-7f46aa5e-d026-4176-8a6f-30058cd30685.png)


> Can u try to remove the .client after discord_ui? so: `from discord_ui import UI`

**Comment by EpicBirb** [comment]
Failed to import discord_ui on 5.1.2

![image](https://user-images.githubusercontent.com/68750348/145652657-c714c0ea-e783-480e-b9e2-eeac84c4d621.png)

**Comment by EpicBirb** [comment]
More context for above screenshot:
![image](https://user-images.githubusercontent.com/68750348/145652800-f0fcb88b-8f3c-484c-a1c8-472e9816e260.png)

**Comment by 404kuso** [comment]
can you import `discord`? A `discord` package sould be installed together with nextcord for migration support. It seems that the discord package is not existing (`'discord' (unknown location)`)


just try a simple import
```py
import discord
from discord import __version__
```

**Comment by EpicBirb** [comment]
> can you import `discord`? A `discord` package sould be installed together with nextcord for migration support ('alias'). It seems that the discord package is not existing (`'discord' (unknown location)`)
> 
> can you try a simple import and tell me the output?
> 
> ```python
> import discord
> from discord import __version__
> ```

![image](https://user-images.githubusercontent.com/68750348/145679680-9f5e44b7-e6d5-4a6a-a05a-3ce5fcb7c7c5.png)

**Comment by 404kuso** [comment]
huh that's weird. Can you try to reinstall nextcord? I tried reproducing that and in my case both imports didn't raise any exceptions.

```batch
py -3.10 -m pip uninstall nextcord && py -3.10 -m pip install nextcord
```

My ouput was:
```
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
>>> from discord import __version__
>>>
```

Btw thank you very much for your patience!

**Comment by EpicBirb** [comment]
It works perfectly now, thank you :D
