### ISSUE TITLE
Nextcord does not work with discord-ui

### ISSUE THREAD

**Issue by CraftDev222** [discord-py-ui/discord-ui#114]
Hey, I tried today to rewrite my Discord bot to Nextcord but somehow I can't because discord-ui requires discord.py and the lib of Discord-UI doesn't support Nextcord, is there any way to fix this?

Before the question comes up, I am using discord-ui version 5.1.5

**Comment by 404kuso** [comment]
discord-ui should work together with nextcord, do you have an exception or something for me?

> I can't because discord-ui requires discord.py

what exaclty do you mean by that? if you mean the imports, discord-ui uses the `discord` module which will be replaced by nextcord during the installation

**Comment by CraftDev222** [comment]
![image](https://user-images.githubusercontent.com/67182201/150641074-ef829614-ced1-4adb-b85a-c5a91b54e6e2.png)

**Comment by CraftDev222** [comment]
And discord.py is not installed there

**Comment by 404kuso** [comment]
can you try to reinstall nextcord?

**Comment by CraftDev222** [comment]
reinstall both?

**Comment by CraftDev222** [comment]
Did it, now it works. Thank you!
