### ISSUE TITLE
Replies are broken

### ISSUE THREAD

**Issue by tiltowait** [discord-py-ui/discord-ui#95]
Performing a simple `await ctx.reply()` does not actually reply. The message is sent without tying it to the appropriate message/context.

The same is true for `await ctx.message.reply()`.

**Comment by 404kuso** [comment]
aight, sorry for the late reply and thx for reporting this issue.

do you have a small code snippet for it? Because there shouldn't exist an `.reply` function in any context

**Comment by 404kuso** [comment]
if you try to reply to a message on an component interaction it should work properly

```py
@bot.listen()
async def on_button_press(ctx):
    await ctx.message.reply("reply")
    await ctx.respond("response")
```

![image](https://user-images.githubusercontent.com/50300929/132089090-10a8a26e-7fcb-4337-8502-aacce1b36d5a.png)

**Comment by tiltowait** [comment]
As of 4.2.6, replies seem to behave correctly now with no code change on my part. Looking through the commits since 4.2.2, nothing leaps out to me in particular as having been the culprit, so whatever you did, thanks!

**Comment by 404kuso** [comment]
np and still thx for reporting
