### ISSUE TITLE
discord_ui.Message.wait_for("select" ...) returns a ComponentContext, not SelectedMenu

### ISSUE THREAD

**Issue by tiltowait** [discord-py-ui/discord-ui#96]
According to [the docs](https://discord-ui.readthedocs.io/en/latest/components.html?highlight=wait_for#discord_ui.Message.wait_for), `discord_ui.Message.wait_for("select", ...)` returns a `SelectedMenu` item; however, in my testing, it returns a `ComponentContext` object. Importantly, the latter lacks a `selected_values` item; in order to access the selection, I have to use `component.data["values"]`.

This discrepancy also affects [this line](https://github.com/discord-py-ui/discord-ui/blob/e92cf849df63ab5538b50e7cb0f9669d5a8cbf60/examples/role_picker.py#L42) in the example code.

**Comment by 404kuso** [comment]
I tried to reproduce it with the example code but for me it works, it gives me a SelectMenu with `.selected_values`, maybe try to update?

**Comment by 404kuso** [comment]
ah wait now I got the issue! I'll fix it

**Comment by 404kuso** [comment]
Okay seems like I somehow already fixed it, I just gotta upload the new version, thx for reporting! ❤

**Comment by 404kuso** [comment]
okay this should be fixed in [`v4.2.14`](https://pypi.org/project/discord-ui/4.2.14/)
